# Numpy Assignment
### Submitted by Pawan Kumar (pavan11896@gmail.com)

In [5]:
# creating a matrix with output columns based on input vector (N) 

import numpy as np
x = np.array([1,2,3,4,5])
N = 5
matrix = np.vander(x,N,increasing=False)
print(matrix)


[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [7]:
# testing
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
N = 3
mat = np.vander(x,N,increasing=False)
print(mat)


[[    9     3     1]
 [   25     5     1]
 [   49     7     1]
 [    4     2     1]
 [   64     8     1]
 [  100    10     1]
 [  121    11     1]
 [ 4225    65     1]
 [ 5184    72     1]
 [ 6561    81     1]
 [ 9801    99     1]
 [10000   100     1]
 [22500   150     1]]
